// eslint-disable-next-line import/prefer-default-export
export const DEFAULT_OPTION = {
  value: 'none',
  displayLabel: 'Choose an option',
};

export const EXPERIENCE_GRADE = [
  {
    value: 0,
    displayLabel: 'No work experience',
  },
  {
    value: 6,
    displayLabel: '6 months',
  },
  {
    value: 12,
    displayLabel: '1 year',
  },
  {
    value: 18,
    displayLabel: '1.5 years',
  },
  {
    value: 24,
    displayLabel: '2 years',
  },
  {
    value: 30,
    displayLabel: '2.5 years',
  },
  {
    value: 36,
    displayLabel: '3 years',
  },
  {
    value: 48,
    displayLabel: '4 years',
  },
  {
    value: 60,
    displayLabel: '5 years',
  },
  {
    value: 72,
    displayLabel: '6 years',
  },
  {
    value: 84,
    displayLabel: '7 years',
  },
  {
    value: 96,
    displayLabel: '8 years',
  },
  {
    value: 108,
    displayLabel: '9 years',
  },
  {
    value: 120,
    displayLabel: '10 years',
  },
  {
    value: 132,
    displayLabel: 'More than 10 years',
  },
];

export const DEVELOPMENT_JOB_OPTIONS = [
  {
    value: 'none',
    displayLabel: 'Choose an option',
  },
  {
    value: 'Solidity',
    displayLabel: 'Solidity',
  },
  {
    value: 'JavaScript',
    displayLabel: 'JavaScript / Front-End',
  },
  {
    value: 'Python',
    displayLabel: 'Python',
  },
  {
    value: '.NET',
    displayLabel: 'C# / .NET',
  },
  {
    value: 'Android',
    displayLabel: 'Android',
  },
  {
    value: 'C++',
    displayLabel: 'C / C++ / Embedded',
  },
  {
    value: 'Flutter',
    displayLabel: 'Flutter',
  },
];

export const ENGLISH_LEVELS = [
  { value: 'basic', displayLabel: 'Basic' },
  { value: 'conversational', displayLabel: 'Conversational' },
  { value: 'fluent', displayLabel: 'Fluent' },
  { value: 'proficient', displayLabel: 'Proficient' },
];

export const EMPLOYMENT_TYPES = [
  { value: 'full_time', displayLabel: 'Full-time' },
  { value: 'part_time', displayLabel: 'Part-time' },
  { value: 'remote_work', displayLabel: 'Remote' },
  { value: 'gig', displayLabel: 'Gig (one-time project)' },
  { value: 'relocation', displayLabel: 'Relocation' },
];

export const SKILLS = [
  'C#',
  '.NET',
  'Entity Framework',
  'Git',
  'LINQ',
  'OOP',
  'REST API',
  'SQL',
  'SOLID',
  '.NET Core',
  'JavaScript',
  'Design Patterns',
  'MVC',
  'Azure',
  'MS SQL Server',
  'HTML',
  'Docker',
  'MSSQL',
  'CSS',
  'ASP.NET',
  'microservices',
  'TypeScript',
  'ASP.NET MVC',
  'jQuery',
  'WPF',
  'Angular',
  'ASP.NET Core',
  'WinForms',
  'Redis',
  'React',
  'ADO.NET',
  'AWS',
  'MongoDB',
  'PostgreSQL',
  'WCF',
  'RabbitMQ',
  'MySQL',
  'T-SQL',
  'Scrum',
  '.Asp.Net Core',
  'Kubernetes',
  'Dapper',
  'Bootstrap',
  'XML',
  'JSON',
  'Agile',
  'Angular 2+',
  'Jira',
  'NUnit',
  'MS SQL',
  'Entity Framework Core',
  'Multithreading',
  'TFS',
  'AJAX',
  'DDD',
  'OOP/OOD',
  'CI/CD',
  'ASP .NET MVC',
  'ASP .NET Core',
  'Elasticsearch',
  'Microservices',
  'NoSQL',
  'xUnit',
  'Jenkins',
  'CQRS',
  'GIT',
  'Unit testing',
  'SignalR',
  'TDD',
  'Azure Service Bus',
  'Oracle',
  'Node.js',
  'TeamCity',
  'C++',
  'HTML5',
  'Visual Studio',
  '.Entity Framework',
  'SVN',
  'Azure Devops',
  'REST',
  'ASP.NET Web API',
  'Azure Blob Storage',
  'Blazor',
  'Agile  Scrum',
  'EF Core',
  'Asyncronous Programming',
  'gRPC',
  'Redux',
  'AngularJS',
  '\u0421#',
  'MVVM',
  'Swagger',
  'AutoMapper',
  'Algorithms and Data Structures',
  'Rabbit MQ',
  'Moq',
  'Postman',
  'Python',
  'Azure Functions',
  'Vue.js',
  'CSS3',
  'Mongo DB',
  'Dependency Injection',
  'Xamarin',
  'Microservice architecture',
  'Web API',
  'DevExpress',
  'SQLite',
  'IIS',
  'Microsoft SQL Server',
  'ASP .NET WebApi',
  'Microsoft Azure',
  'web development',
  'ASP.NET Core Web API',
  'Amazon AWS',
  'GitHub',
  'Kafka',
  'PowerShell',
  'C#/.NET',
  'MSSQL/T-SQL',
  'Angular.js',
  'ASP .NET Web API',
  'XUnit',
  'XAML',
  'JIRA\u200d',
  '.Net Web API',
  'GraphQL',
  'Terraform',
  'CQRS/MediatR',
  'WebAPI',
  'Linux',
  'ASP.NET Core SignalR',
  'NHibernate',
  'ASP. NET WEB API',
  'Hangfire',
  'Elasctisearch',
  'ASP.NET WebAPI',
  'Micro-service architecture',
  'AWS S3',
  'SOAP',
  'Unity',
  'WebServices',
  'Azure Application Insights',
  'Autofac',
  'Unit Testing',
  'PL/SQL',
  'UWP',
  'Windows Forms',
  'DRY',
  'ADO.NET/Entity framework',
  'Java',
  'C/C++',
  'JWT',
  'Azure App Service',
  'Kanban',
  'Azure DevOps',
  'RabbiMQ',
  'GitLab',
  'Android',
  '.Net Framework',
  'MassTransit',
  'AWS Lambda',
  'algorithms',
  'React+Redux',
  'Unit Test',
  'JS',
  'RESTful API',
  '.Net Core',
  'MS SQL/PostgreSQL',
  'Test driven development',
  '.NET C#',
  'Docker Compose',
  'Apache Kafka',
  'Software Design',
  'software architecture',
  '.NET Core 3.1',
  'Clean Architecture',
  'SCSS',
  'API REST',
  'F#',
  'Web/ WCF services',
  'RxJS',
  'Architectural Patterns',
  'Database: MSSQL',
  'ASP.NET CORE',
  'Confluence',
  'UnitTesting',
  'Grafana',
  'KISS',
  'Domain Driven Design',
  'Backend development',
  '-\tC#',
  'PHP',
  'C #',
  'HTML & CSS',
  'MSUnit',
  'Azure Fuctions',
  'MicroServices',
  'GCP',
  'Event Sourcing',
  'ASP.NET CORE [MVC 3-5]',
  'team management',
  'GIT / TFS / SVN',
  'Octopus',
  '.NET / C #',
  'Atlassian Jira',
  'SonarQube',
  'React.js',
  'Mongo',
  '.NetCore',
  'SQLServer',
  'serverless',
  'Azure Cosmos DB',
  'Unit/Integration tests',
  'ASP.NET MVC 5',
  'patterns',
  'SOLID/DRY/KISS/YAGNI',
  'Agile / Scrum',
  'Bitbucket',
  'NgRx',
  'Unity3D',
  'Vue',
  '. NET',
  'Database design',
  'TSQL',
  'OAuth',
  'API',
  'project management',
  'OAuth 2.0',
  'Xamarin Forms',
  'SASS',
  'Golang',
  'MediatR',
  'Microsoft Visual Studio',
  'ASP Web API',
  'WPF/MVVM Pattern',
  'Postgre SQL',
  'WinAPI',
  'Postgres',
  'ASP Core',
  'Azure Storage',
  'Selenium WebDriver',
  '.net 6.0',
  'AWS EC2',
  'CodeReview',
  'distributed systems',
  'Docker containers',
  'Xamarin.Forms',
  'ADO .NET',
  'ASP.NET Core MVC',
  'Kibana',
  'OOD',
  'CI / CD',
  'NServiceBus',
  'Dapper.NET',
  'k8s',
  'Windows Services',
  'CI',
  'Cosmos DB',
  'Azure API Management',
  'DI/IoC',
  'ASP',
  'ElasticSearch',
  '.NET 4.6 / CORE 2.0',
  '.Net C #',
  'Microservies',
  'Azure Pipelines',
  'UML',
  'Unit tests',
  'ASP.NET WebForms',
  'React Hooks',
  'Unity 3D',
  'Cloud',
  'Knowledge of SQL',
  'BitBucket',
  'English',
  'CosmosDB',
  'Team Lead',
  'AGILE / SCRUM',
  'C# winforms',
  'DevOps',
  'Angular 8',
  'FluentValidation',
  'Code refactoring',
  'Event Driven Architecture',
  'Azure SQL',
  'Full-stack Web Development',
  'EntityFramework',
  'EF',
  'Delphi',
  'TPL',
  'Message brokers',
  'React Native',
  'Entity Fram. Core',
  'Serilog',
  'JQuery',
  'Angular 12',
  'Automated Testing',
  'Nginx',
  'iOS',
  'AWS SQS/SNS',
  'Kendo UI',
  'Full Stack',
  'Azure Active Directory',
  'Databases: MySQL',
  'fullstack',
  'Figma',
  'highload',
  'Continuous Integration',
  'Product Management',
  'Waterfall',
  'TCP/IP',
  'NSubstitute',
  'Selenium',
  '.NET FULL/CORE',
  'Oracle DB',
  'ELK',
  'C# WPF',
  'Umbraco',
  'Azure App Services',
  'Azure Service Fabric',
  'NLog',
  'NET Core',
  'Basics HTML/CSS',
  'ASP.NET Identity',
  'Dynamics 365',
  'Angular Material',
  'API Testing',
  'SQL Server',
  'Angular 2',
  'Node JS',
  'ASP.NET Web API 2',
  'Microsoft Team Foundation Server',
  'NET Framework',
  'Azure Event Hub',
  '.net 5.0',
  'SpecFlow',
  'NUnit Framework',
  'web.api',
  'Firebase',
  'ExtJS',
  'Telerik',
  'Java Script',
  'Data Structures',
  'Refactoring',
  'team leadership',
  'Scala',
  'MS Visual Studios',
  '.Net Core 2',
  'integration testing',
  'EF Code First',
  'Flutter',
  'WebSocket',
  'FrontEnd',
  'API Documenting',
  'Networking',
  'IoT',
  'Dynamics CRM',
  'AutoFixture',
  'Xamarin.Android',
  '.net mvc',
  'Razor Pages',
  'API Integration',
  'Team leading',
  'SOLID/TDD/BDD/KISS',
  'Machine Learning',
  'CICD',
  'HTML5 &amp; CSS3',
  '.NET 6',
  'asp net core',
  'Postman.',
  'C#.NET',
  'ssis',
  'problem solving',
  'ASP.Net Core 2.0',
  'MSTest',
  'Visual Basic',
  'clean code',
  'Entity Framework / Core',
  'RX',
  'Azure Cloud',
  'IdentityServer4',
  'GitHub Actions',
  'AzureDevOps',
  'Asp.Net WepApi',
  'Event Bus',
  'MVC/ MVP/ MVVM',
  'VB.NET',
  'PLSQL',
  'Azure SQL Database',
  'Docker Swarm',
  'UnitTests',
  'Unit + Integretion testing',
  'Unit test',
  'Blazor server side',
  'SSRS',
  '3D modeling',
  'Technical Leadership',
  'IoC',
  'SPA',
  'Angular 7',
  'LESS',
  'C# .NET',
  'ASP.NET CORE /RAZOR/WEB API',
  'AWS API Gateway',
  'AWS DynamoDB',
  'Webpack',
  'DI',
  'ASP.NET 5',
  'Visual Studio Code',
  'Team Leadership',
  'http',
  'code review',
  'SharePoint',
  'Performance profiling and optimization',
  'Sitecore',
  'XSLT',
  'HTML/XML/JSON/Bootstrap',
  'ES6',
  'ASP.NET Web Forms',
  'BDD',
  'Cassandra',
  'Prometheus',
  'MS Visual Studio',
  'Design architecture',
  'ASP.NET MVC -\tEntity Framework',
  'Unit / Integration / E2E Testing',
  'Team City',
  '.NET platform/Core',
  'JavaScript/jQuery',
  'MySQL Server',
  'Azure Queues',
  'FluentAssertions',
  'CRM',
  'Mercurial',
  'ActiveMQ',
  'RDBMS',
  'AWS services',
  'Knowledge of HTML/CSS',
  'Azure Key Vault',
  'Azure Kubernetes Service',
  'GIT SVN',
  'Code First',
  'asynchronous programming',
  'ClickHouse',
  'Azure Services',
  'Razor',
  'Helm',
  'Web API 2',
  'SQLLite',
  'ASP Identity',
  'Generic Repository Pattern',
  'mentoring',
  'CQRS + ES',
  'ORM',
  'JIRA / Git / Jenkins / code review',
  'Oracle DB 11g',
  'game development',
  'backend',
  'Saga',
  'Stored Procedures',
  'SSAS',
  'Redmine',
  'C#:  .net framework',
  'Resharper',
  'Gitlab CI/CD',
  'RESTful web services',
  'HTML / CSS / JavaScript / TypeScript',
  'Hibernate',
  'MySQL/Postgres',
  'Prism',
  'Web Socket',
  'nuget',
  'Azure AD',
  'Angular 10',
  'Spring',
  'Big Data',
  'Google Cloud',
  'Subversion',
  'Microsoft Bot Framework',
  'Knockout.js',
  'Xamarin.iOS',
  'performance optimization',
  'Azure Storage Account',
  'Identity Server',
  'Azure CosmosDB',
  'SingleSPA',
  'GoLang / Go',
  'MSSQL Server',
  'DynamoDB',
  'Architectural design patterns',
  'Twilio',
  'Git &amp; Gitlab / Bitbucket',
  '.NET FULL / CORE',
  'EFCore',
  'Swashbuckle.AspNetCore',
  'Azure IoT Hub',
  '.NET 4.5',
  'Client/Server',
  'HTML5 & CSS3',
  'Ocelot',
  'Agile methodology',
  'ASP.NET Core WebApi',
  'EF FULL/CORE',
  'Actor Model',
  'Software Development Life Cycle',
  'ASP.NET Core 2.2',
  'bash',
  'YAML',
  'odata',
  'VBScript',
  'ARM Templates',
  '\u041f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 C#',
  'Trello',
  'Swift',
  'Windows Phone',
  'log4net',
  'Repository Pattern',
  'DevExtreme',
  'AWS RDS',
  'C# Async',
  'C++/CLI',
  'Structured Logging',
  'Push Notification',
  'AWS SNS',
  'Security',
  '.Net Core 3',
  'back-end',
  '.net core',
  'Regular Expressions',
  'Azure Table Storage',
  'Azure SQL Server',
  'Angular 1.x',
  'Auth0',
  'Photoshop',
  'MVP',
  'architecture',
  'ASP.Net',
  'ASP.NET MVC Core',
  'AWS CloudFormation',
  'AWS ElasticSearch',
  'Solidity',
  'Microsoft Windows',
  'refactoring',
  'Jest',
  'ES6+',
  'Azure Web Services',
  'communication skills',
  'NextJs',
  'Windows',
  'Material UI',
  'MobX',
  'Message Queues',
  'Blockchain',
  'Cloud Architecture',
  'Angular2',
  'Firebird',
  'Web applications',
  'CI/CD/CT',
  'Adobe Photoshop',
  'FluentMigrator',
  'Git Flow',
  'MySql Databases',
  'ASP NET Forms',
  'MSSQ',
  'Kotlin',
  'Lambda',
  'MvvmCross',
  'Oracle SQL',
  'math',
  'SOA',
  'API testing',
  'JS/JQuery/Ajax/JSON',
  'OOP principles',
  'Ionic',
  'IdentityServer',
  'Asp WebApi',
  'RebbiMQ',
  'Mathematics',
  '.NET MAUI',
  'Azure WebJobs',
  'Web Forms',
  'Azure Logic Apps',
  'GitlabCI',
  'Test driven development ',
  'Azure AD B2C',
  'Power Apps',
  'GDPR',
  'Microsoft SharePoint',
  'OpenCV',
  'Source Tree',
  'Wix',
  'Xamarin.Native',
  'HTTP / npm / Fetch API',
  'Typescript',
  'Azure Event Grid',
  'Knockout',
  'Veracode',
  'EventDrivenArchitecture',
  'Concurrency',
  'LINQ to SLQ',
  'Windows Presentation Foundation',
  'Event-driven-archtecture',
  'Angular 9',
  'npm',
  'WPF / MVVM Pattern',
  'Asana',
  'Algorithms/Data Stucture',
  'ASP.NET Core 2-3.1',
  'Windows Server',
  'Amazon DynamoDB',
  'Arduino',
  'c# developer',
  'Memcached',
  'Mediator Pattern',
  'SQS',
  'AWS Cognito',
  'Sentry',
  'Multilayer arcitecture',
  'WebSockets',
  'C# / .Net',
  'Apache Solr',
  ': Git',
  'VS Code',
  'KnockoutJS',
  'Vuex',
  'Silverlight',
  'GameDev',
  'mobile games',
  'Unity Particles system',
  'Blender',
  'Architect',
  'Manual Testing',
  'Web Sockets',
  'Scrum/Agile',
  'AWS Athena',
  'Distributed Systems',
  '3D graphics',
  'c',
  'Apache',
  'Software Architecture',
  'ASP.NET Boilerplate',
  'dotMemory',
  'Azure Cognitive Search',
  'Django',
  '\u041f\u0438\u0448\u0443 \u043d\u0430 \u044f\u0437\u044b\u043a\u0435 C#',
  '\u041e\u041e\u041f',
  'NET',
  'JMeter',
  'Quartz.NET',
  'AWS ECS',
  'analytical skills',
  'English - advanced',
  'WebApi2',
  'Benchmark',
  'good communication skills',
  'Microsoft Office',
  'Angular 4+',
  'HTML5 / XHTML / XML',
  'Oracle Database.',
  'SignalR Core',
  'Appium',
  'Win32',
  'Xcode',
  'Lua script',
  'git/svn',
  'work in team.',
  'NATS',
  'Vue / Vuex',
  'Angular 11',
  'Power Platform',
  'Serverless',
  'Hadoop',
  'Gremlin',
  'Solr',
  'Python basics',
  'Twitter Bootstrap',
  'Application Architectures',
  'Strong SQL',
  'Service Fabric',
  'MS Access',
  'interviews &amp; mentoring',
  'AWS Step Functions',
  'integration',
  'ui',
  'asp.net Web API 2.0',
  'Akka.NET',
  'Team managment',
  'Team coordination',
  'Azure KeyVault',
  'Nats',
  '.NET Development',
  'SendGrid',
  '.Net Core 5',
  'Ninject',
  'Load Balancer',
  'Express.js',
  'NGRX',
  'NEST',
  'MS Orleans',
  'Microsoft SQL Server Management Studio',
  'ANTLR',
  'Seq',
  'Salesforce',
  'RestAPI',
  'git-flow',
  'WinRT',
  'Gathering software requirements',
  'SSO',
  'MVC ASP.NET',
  'Functional Programming',
  'Basic knowledge of JavaScript',
  'functional testing',
  'Shell',
  'Ansible',
  'WebForms ASP.NET',
  'WPF .NET',
  'AppInsights',
  'Class Library',
  'SOLID principles',
  'OWASP',
  'Azure EventHub',
  'delivery management',
  'Caliburn.Micro',
  'Haxe',
  'Visual Basic ',
  'PCI DSS',
  'interviews & mentoring',
  'Multitenancy',
  'NetCore',
  'MemoryCache',
  'Solutions Architecture',
  'Highload systems',
  'technical documentation',
  'Automated Testing ',
  'Agile Software',
  'Reporting Services',
  'microservices architecture',
  'IoC/DI',
  'Angular 6',
  'Windows service',
  'Cryptography',
  'Objective-C',
  'Visual Studio Team System',
  'Data Warehouse',
  'PySpark',
  'CQRS Pattern',
  'Image Proessing',
  'MS Access VBA',
  'Consul',
  'Hashicorp Vault',
  'Lisp',
  'Python3',
  '.NET5',
  'VB 6.0/VBA',
  'ETL',
  'Bootstrap 4',
  'Rider IDE',
  'Haskell',
  'rust',
  'Black Duck',
  'Foritfy',
  'Message Queuing',
  'Lucene',
  'Telegram Bot API',
  'RxJava',
  'RxAndroid',
  'Mender.io',
  'RDF',
  'OpenID',
  'Firestore',
  'BASH',
  'ASP.NET Forms MVC',
  'SNS/SQS',
  'GoogleAnalytics',
  'Integration events',
  'RequireJS',
  'WIX toolset',
  'HTML/CSS',
  'Specflow',
  'Google',
  'Amazon',
  'Azure Cloud Platform',
  'Databricks',
  'Postman API',
  'nopCommerce',
  'Jasmine',
  'prototyping',
  'game design',
  'Adobe Illustrator',
  'Game Creator',
  'MS Azure',
  'SAP Business One',
  'YARP',
  'TargetProcess',
  'Mantis',
  'VSTS',
  'Azure Blockchain Workbench',
  'DirectX',
  'Amazon EC2',
  'AWS SQS',
  'R ',
  'Basic knowledge of SQL',
  'Frontend + Backend',
  'Frontend Development',
  'React / Redux',
  'Angular 2 - 11',
  'Tableau Server',
  'AWS CloudWatch',
  'Product Roadmap',
  'Business Operations',
  'project planning',
  '.NET Back-end Development',
  'Krakow',
  'Crystal Reports',
  'QuickFix',
  'FIX Protocol',
  'PowerBI',
  'BitBuket',
  'KustoQueryLanguage',
  'Telemetry',
  'async',
  'DocuSign',
  'billing',
  'erp',
  'Gold Stock',
  'Gold Vocal',
  'Manhattan Scale WMS',
  'Microsoft Dynamics AX',
  'WMS',
  'test case',
  'api 2.0',
  'Putty',
  'WinSCP',
  'X++',
  'Qt',
  'Service Desk',
  'business development',
  'customer support',
  'HelpDesk',
  'BI Analyst',
  'fo365',
  'Microsoft Dynamics 365 for Finance and Operations',
  'business analysis',
  'Minimal API',
  'WinForm',
  'HTML &amp; CSS',
  '.Net',
  'Alexa',
  'd3js',
  'ORMLite',
  'Node-RED',
  'Dynamics 365 CRM',
  'Model-Driven Application',
  'Laravel',
  'PHPUnit',
  'Solution Architecture',
  'Data Engineering',
  'Spark',
  'Azure DevOps CI/CD',
  'WinStore',
  'HTML/JS/JQuery',
  'Drupal',
  'Wordpress',
  '\u0420\u0435\u0444\u0430\u043a\u0442\u043e\u0440\u0438\u043d\u0433',
  'Azure Cognitive Services',
  'LUIS',
  'Basic MongoDb',
  'Basic OracleSQL',
  'NetsJS',
  'TailwindCSS',
  'React-Native',
  'Service Bus',
  'Risk Management',
  'Leading teams',
  'Elastic',
  'AWS Glue',
  'Keycloak',
  'Soft skills',
  'Erwin',
  'ActiveDirectory',
  'Sybase ASA',
  'JavaScript \\ TypeScript \\ ECMAScript',
  'EC2',
  'Azure Compute',
  'AWS Route53',
  'mono',
  'Microsoft Azure Functions',
  'ECS',
  'GRASP',
  'MangoDB',
  'Ruby on Rails',
  'Perl',
  'cql',
  'Vue. JS',
  'MSSQL:SSIS\\SSAS\\SSRS',
  'DApp',
  'EVM',
  'FuelUX',
  'Couchbase',
  'Linq2Db',
  'SSMS',
  'Bitcoin',
  'Ethereum',
  'Garbage Collection',
  'Cloud DevOps',
  'neural networks',
  'Artifactory',
  'Data Science',
  'Google Cloud Platform',
  'Tibco',
  'Software Engineering Practices',
  'software maintenance',
  'skiasharp',
  'BluetoothLE',
  'Okta',
  'PDF',
  'DBMS',
  'SAFE',
  'abp.io',
  'asp.net mvc',
  'Agile Kanban',
  '.Net Core NUnit',
  'Atlassian Connect Express',
  'Atlassian Forge',
  'KendoUI',
  'UIKit',
  'Memory Management',
  'functional programming',
  'Hawkbit',
  'VirtualBox',
  'Vagrant',
  'Nuke Build',
  'Apache Ignite',
  'Stripe',
  'cypress.io',
  'Management Hard Skills',
  'Database First',
  'Cloud patterns',
  'Cybersecurity',
  'Azure DPS',
  'Polly',
  'IaC',
  'Cloud Design Patterns',
  'process management',
  'people management',
  'Celery',
  'Foundation',
  'Pyramid',
  'Underscore.js',
  'Architectural Programming',
  'XPath',
  'Agile ',
  'Sphinx',
  'dotTrace',
  'Web Form',
  'AD',
  'WPF Prism',
  'SQL Azure',
  'RavenDB',
  'Airflow',
  'concourse',
  'FoxPro',
  'Elsa workflow',
  'TPL Dataflow',
  'Scrumban',
  'ATAM',
  'Neo4j',
  'High Performance Computing',
  'MSMQ',
  'FinTech',
  'Banking & Finance',
  'Payment & Processing',
  'WSL',
  'Microsoft Visual Studio IDE',
  'JavaScript / NodeJS',
  '.NET 5',
  'leadership',
  'physics',
  'WebAssembly',
  'stored procedure',
  'Compilers',
  'Fuzzy Logic',
  'PHP5',
  'asterisk voip',
  'LAMP',
  'Basics of HTML and CSS',
  'Microsoft Orleans',
  'Apache Spark',
  'Azure Synapse',
  'Monitoring',
  'Azure Development',
  'Autodesk Forge APIs',
  'Forge Viewer',
  'Autodesk Revit API',
  'Asp.Core',
  'ReactJs',
  'JavaCard',
  'Code Quality',
  'AOP',
];

export const COUNTRIES_LIST = [
  { name: 'Select your country', code: 'none' },
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'AndorrA', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People'S Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'RWANDA', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia and Montenegro', code: 'CS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];

// <select class="form-control js-update-avg-salary" required="" name="primary_keyword_cache" id="primary_keyword">
//                 <option value="">- Choose an option -</option>

//                   <optgroup label="Development">

//                       <option value=".NET">C# / .NET</option>

//                       <option value="Android">Android</option>

//                       <option value="C++">C / C++ / Embedded</option>

//                       <option value="Flutter">Flutter</option>

//                       <option value="Golang">Golang</option>

//                       <option value="iOS">iOS</option>

//                       <option value="Java">Java</option>

//                       <option value="JavaScript">JavaScript / Front-End</option>

//                       <option value="Node.js">Node.js</option>

//                       <option value="PHP">PHP</option>

//                       <option value="Python">Python</option>

//                       <option value="Ruby">Ruby</option>

//                       <option value="Rust">Rust</option>

//                       <option value="Scala">Scala</option>

//                   </optgroup>

//                   <optgroup label="Other (tech)">

//                       <option value="Business Analyst">Business Analyst</option>

//                       <option value="Data Science">Data Science</option>

//                       <option value="Data Analyst">Data Analyst</option>

//                       <option value="Data Engineer">Data Engineer</option>

//                       <option value="DevOps">DevOps</option>

//                       <option value="Design">Design / UI/UX</option>

//                       <option value="Artist">2D/3D Artist / Illustrator</option>

//                       <option value="Unity">Gamedev / Unity</option>

//                       <option value="Product Manager">Product Manager</option>

//                       <option value="Project Manager">Project Manager</option>

//                       <option value="Scrum Master">Scrum Master / Agile Coach</option>

//                       <option value="QA Automation">QA Automation</option>

//                       <option value="QA">QA Manual</option>

//                       <option value="SQL">SQL / DBA</option>

//                       <option value="Security">Security</option>

//                       <option value="Sysadmin">Sysadmin</option>

//                       <option value="Lead">Architect / CTO</option>

//                       <option value="SEO">SEO</option>

//                   </optgroup>

//                   <optgroup label="Other (non tech)">

//                       <option value="Marketing">Marketing</option>

//                       <option value="HR">HR</option>

//                       <option value="Recruiter">Recruiter</option>

//                       <option value="Sales">Sales</option>

//                       <option value="Support">Customer/Technical Support</option>

//                       <option value="Technical Writing">Technical Writing</option>

//                       <option value="Lead Generation">Lead Generation</option>

//                       <option value="Other">(Other)</option>

//                   </optgroup>

//               </select>
